name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: prep crabfetch
        run: |
          git clone git@github.com:LivacoNew/CrabFetch.git
          cd CrabFetch
          cargo build -r
          chmod +x ./target/release/crabfetch
      - name: run crabfetch
        run: ./target/release/crabfetch
